-- AlterEnum
ALTER TYPE "BookingStatus" ADD VALUE 'CANCELLED_BY_CLIENT';
ALTER TYPE "BookingStatus" ADD VALUE 'CANCELLED_BY_COMPANY';

-- AlterEnum
ALTER TYPE "FlightStatus" ADD VALUE 'CANCELLED_BY_CLIENT';
ALTER TYPE "FlightStatus" ADD VALUE 'CANCELLED_BY_COMPANY';
